version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/swiftchain
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - swiftchain-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - swiftchain-network

networks:
  swiftchain-network:
    driver: bridge

volumes:
  mongo-data:
